module.exports = {
  //coding languages
  xml: "xml",
  javascript: "javascript",
  python: "python",
  php: "php",
  go: "go",
  rust: "rust",
  sql: "sql",
  modules: {
    toolbar: [
      ["bold", "italic", "underline", { color: [] }],
      [{ list: "ordered" }, { list: "bullet" }, { align: [] }],
      ["clean"],
    ],
  },
  formats: [
    "header",
    "bold",
    "italic",
    "underline",
    "color",
    "list",
    "bullet",
    "align",
  ],
  fullScreenModules: {
    toolbar: [
      ["bold", "italic", "underline", "strike", "blockquote"],
      [{ list: "ordered" }, { list: "bullet" }],
      [{ color: [] }, { background: [] }],
      [{ header: [1, 2, 3, false] }],
      [{ script: "sub" }, { script: "super" }],
      [{ font: [] }],
      [{ align: [] }],
    ],
  },
  fullScreenFormats: [
    "bold",
    "italic",
    "underline",
    "color",
    "strike",
    "blockquote",
    "list",
    "bullet",
    "indent",
    "script",
    "header",
    "background",
    "align",
    "font",
  ],
  uploadModules: {
    toolbar: [
      ["bold", "italic", "underline", { color: [] }],
      [{ list: "ordered" }, { list: "bullet" }, { align: [] }],
      ["clean"],
    ],
  },
  uploadFormats: [
    "header",
    "bold",
    "italic",
    "underline",
    "color",
    "list",
    "bullet",
    "align",
  ],
  tutorialSteps: ["Tutorial by ", "Create your own", "Preview your tutorial"],
  tooltipMsg: [
    "Create a step to explain a passage in the video. After you save it, check it in the Preview section.",
    "Check and publish your tutorial so everyone can learn from it!",
  ],
  months: [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ],
  category: [
    "All",
    "Tech",
    "Music",
    "Education",
    "Recipes",
    "Live",
    "Lifestyle",
    "Workout",
  ],
  filterConstant: ["Most recent", "Most viewed", "Highest rated"],
  steps: ["Upload Video", "Video Information", "Thumbnails", "Complete Upload"],
  stepContent: [
    "Upload your video here, any extension is accepted",
    "Insert some information about the video like a title, a description or the categories it belongs to, in order to make it easier for the viewer to search through #hashtags. Also decide if you want it to be a public or a private video, allowing other users to make tutorials on it.",
    "You can add one or more thumbnails to the video or even none, leaving the first frame of the video to be the thumbnail.",
    "Check if all the information you inserted are correct, and upload the video.",
  ],
  playbackRates: ["1", "1.5", "2", "0.5"],
  logo: "https://image-bucket-youtorial.s3.eu-central-1.amazonaws.com/80592_Youtorial_FLAT_JH__ref_jh__0000000000000000-removebg-preview.png"
};
